# Generated by Django 3.1.4 on 2020-12-28 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0002_auto_20201227_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='emial',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
